Repository WildCodeSchool/2023-03-JS-TLSE-P3-AFAC974, pull requests merged in 2023-07, with the labels that each got.

#21 S05 us18 artist manager controller
  backend/src/controllers/artistControllers.js
  backend/src/models/ArtistManager.js
  backend/src/router.js
  package-lock.json
Labels: Reviewed

#23 S05 us15 signin login improvements
  backend/database.sql
  backend/src/controllers/userControllers.js
  backend/src/models/UserManager.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/Input.jsx
  frontend/src/components/Login.jsx
Labels: Changes requested

#25 S05US21_about_page
  frontend/src/App.jsx
  frontend/src/assets/logo_regular.png
  frontend/src/pages/About.jsx
Labels: Reviewed

#26 S05US21_about_page
  backend/src/controllers/userControllers.js
  backend/src/models/UserManager.js
  backend/src/router.js
  frontend/src/pages/About.jsx
Labels: Reviewed

#27 S05US21_about_page
  backend/src/models/UserManager.js
Labels: Reviewed

#28 S06_Dev_to_Main_merge
  backend/.env.sample
  backend/database.sql
  backend/src/controllers/artistControllers.js
  backend/src/controllers/userControllers.js
  backend/src/models/ArtistManager.js
  backend/src/models/UserManager.js
  backend/src/router.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/assets/arrow.png
  frontend/src/assets/bg_home.jpg
  frontend/src/assets/logo_regular.png
  frontend/src/components/AddArtwork.jsx
  frontend/src/components/ArtworkForm/ArtworkForm1.jsx
  frontend/src/components/ArtworkForm/ArtworkForm2.jsx
  frontend/src/components/ArtworkForm/ArtworkForm3.jsx
  frontend/src/components/BurgerMenu.jsx
  frontend/src/components/ConfirmationModal.jsx
  frontend/src/components/GalleryButton.jsx
  frontend/src/components/Input.jsx
  frontend/src/components/LanguageMenu.jsx
  frontend/src/components/Login.jsx
  frontend/src/components/NavBar.jsx
  frontend/src/components/ValidationModal.jsx
  frontend/src/pages/About.jsx
  frontend/src/pages/Home.jsx
  package-lock.json
Labels: Reviewed

#29 S05_main_hotfix
  backend/database.sql
  frontend/index.html
  frontend/src/pages/Home.jsx
Labels: Reviewed

#30 Main_hotfix
  backend/database.sql
  frontend/index.html
  frontend/src/pages/Home.jsx
Labels: Reviewed

#31 S05_main_hotfix
  frontend/src/index.css
  frontend/src/pages/Home.jsx
Labels: Reviewed

#32 Hotfix before demo
  frontend/src/index.css
  frontend/src/pages/Home.jsx
Labels: Reviewed

#33 S06US22_gallery_page
  frontend/src/App.jsx
  frontend/src/assets/heart.svg
  frontend/src/assets/heart_red.svg
  frontend/src/assets/search.svg
  frontend/src/components/SearchBar.jsx
  frontend/src/components/SortBy.jsx
  frontend/src/pages/Artwork.jsx
  frontend/src/pages/Gallery.jsx
Labels: Reviewed

#34 S06 us26 user page
  backend/database.sql
  frontend/src/App.jsx
  frontend/src/assets/back-arrow.png
  frontend/src/assets/trash.png
  frontend/src/components/BurgerMenu.jsx
  frontend/src/components/DeleteUser.jsx
  frontend/src/components/Login.jsx
  frontend/src/components/SortBy.jsx
  frontend/src/components/UserCard.jsx
  frontend/src/components/UsersDisplay.jsx
Labels: Reviewed

#36 S06 us23 artwork page
  backend/database.sql
  backend/src/controllers/artistControllers.js
  backend/src/controllers/arttrendControllers.js
  backend/src/controllers/artworkControllers.js
  backend/src/controllers/techniqueControllers.js
  backend/src/controllers/typeControllers.js
  backend/src/models/ArttrendManager.js
  backend/src/models/TechniqueManager.js
  backend/src/models/TypeManager.js
  backend/src/models/index.js
  backend/src/router.js
  frontend/src/App.jsx
  frontend/src/components/FavoriteButton.jsx
  frontend/src/components/SearchBar.jsx
  frontend/src/pages/Artwork.jsx
  frontend/src/pages/Gallery.jsx
Labels: Reviewed

#38 S06 usx connection users pages
  backend/database.sql
  backend/package-lock.json
  backend/package.json
  backend/src/auth.js
  backend/src/controllers/userControllers.js
  backend/src/models/UserManager.js
  backend/src/router.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/assets/prev.png
  frontend/src/assets/settings.png
  frontend/src/components/Login.jsx
  frontend/src/components/PrevPageButton.jsx
  frontend/src/components/RouteComponents.jsx
  frontend/src/context/AuthContext.jsx
  frontend/src/pages/AdminHome.jsx
  frontend/src/pages/ArtworksAdministration.jsx
  frontend/src/pages/Unauthorized.jsx
  frontend/src/pages/UserHome.jsx
  frontend/src/pages/UsersAdministration.jsx
  package-lock.json
  package.json
Labels: Reviewed

#40 S06US29_artist_page_fix_bug functionnal
  frontend/src/components/Carousel.jsx
  frontend/src/components/RouteComponents.jsx
  frontend/src/pages/Artist.jsx
  frontend/src/pages/Artwork.jsx
Labels: Reviewed

#42 S07US30_right_click_deact
  frontend/src/components/Carousel.jsx
  frontend/src/pages/Artist.jsx
  frontend/src/pages/Artwork.jsx
  frontend/src/pages/Gallery.jsx
Labels: Reviewed

#43 S07 usx2 user navigation
  backend/package-lock.json
  backend/src/controllers/userControllers.js
  backend/src/models/UserManager.js
  backend/src/router.js
  frontend/package-lock.json
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/Login.jsx
  frontend/src/components/NavBarUser.jsx
  frontend/src/components/RouteComponents.jsx
  frontend/src/context/AuthContext.jsx
Labels: Reviewed

#44 S07 us33 hamburger improvements
  backend/package-lock.json
  frontend/package-lock.json
  frontend/src/components/BurgerMenu.jsx
  frontend/src/components/Login.jsx
  frontend/src/components/NavBar.jsx
  frontend/src/components/NavBarUser.jsx
Labels: Reviewed

#46 S07 us32 double save problem
  backend/public/tmp/0c95f61ce01d6cb488c2bda6ce4518fe
  backend/public/tmp/964f7ac10edf3614eb786a34a31c8de0
  backend/src/controllers/uploadControllers.js
  backend/src/router.js
  backend/src/services/cloudinary.js
  frontend/src/components/ConfirmationModal.jsx
  frontend/src/components/NavBarUser.jsx
  frontend/src/pages/AdminHome.jsx
  frontend/src/pages/ArtistAdministration.jsx
  frontend/src/pages/ArtworksAdministration.jsx
Labels: Reviewed

#47 S07 us38 modify artist on name
  frontend/src/pages/ArtistAdministration.jsx
Labels: Reviewed

#49 S07 usx2 user navigation
  frontend/src/assets/Frame.png
  frontend/src/assets/Icon.png
  frontend/src/assets/art.png
  frontend/src/assets/log-out.png
  frontend/src/assets/pinceau.png
  frontend/src/assets/user.png
  frontend/src/components/NavBar.jsx
  frontend/src/components/NavBarUser.jsx
Labels: Reviewed

#51 S07 us31 user login input improvements
  backend/src/controllers/entityControllers.js
  backend/src/models/EntityManager.js
  backend/src/models/index.js
  backend/src/router.js
  frontend/src/components/Input.jsx
  frontend/src/components/Login.jsx
  frontend/src/components/UserCard.jsx
Labels: Reviewed

#53 S07US39_admin_hom_artist_users_management
  frontend/src/components/NavBarUser.jsx
  frontend/src/pages/AdminHome.jsx
  frontend/src/pages/ArtistAdministration.jsx
Labels: Reviewed

#54 S07 us43 settings page
  frontend/src/components/NavBarUser.jsx
  frontend/src/components/RouteComponents.jsx
  frontend/src/context/AuthContext.jsx
  frontend/src/pages/AccountSettings.jsx
  frontend/src/pages/AdminHome.jsx
Labels: Changes requested, Corrections done

#55 S07 us20 user image
  backend/src/controllers/userControllers.js
  frontend/src/components/Login.jsx
Labels: Corrections done

#56 S07 us31 user connexion improvements
  backend/src/app.js
  backend/src/controllers/itemControllers.js
  frontend/src/components/AddArtwork.jsx
  frontend/src/components/DeleteUserConfirmation.jsx
  frontend/src/components/FormModify/ArtworkFormModify.jsx
  frontend/src/components/Login.jsx
  frontend/src/components/ValidationModal.jsx
  frontend/vite.config.js
Labels: Reviewed

#57 S07 us36 user favorite page front
  backend/database.sql
  backend/src/controllers/favoriteControllers.js
  backend/src/models/FavoriteManager.js
  backend/src/router.js
  frontend/src/assets/x-lg.svg
  frontend/src/components/FavoriteButton.jsx
  frontend/src/pages/Artwork.jsx
  frontend/src/pages/Gallery.jsx
  frontend/src/pages/UserFavorite.jsx
Labels: Reviewed

#58 Hot fix error console
  frontend/src/components/ArtworkFormAdd/ArtworkForm2.jsx
  frontend/src/components/ArtworkFormAdd/ArtworkForm3.jsx
  frontend/src/components/FormModify/ArtistFormModify.jsx
  frontend/src/components/FormModify/ArtworkFormModify.jsx
  frontend/src/components/ModifyArtist.jsx
  frontend/src/components/ModifyArtwork.jsx
  frontend/src/components/RedButton.jsx
  frontend/src/components/SelectionInput.jsx
  frontend/src/pages/AdminHome.jsx
  frontend/src/pages/ArtworksAdministration.jsx
Labels: Reviewed

#59 S07 us41 user home
  frontend/src/components/Login.jsx
  frontend/src/pages/AdminHome.jsx
  frontend/src/pages/ArtistAdministration.jsx
  frontend/src/pages/ArtworksAdministration.jsx
  frontend/src/pages/UserFavorite.jsx
  frontend/src/pages/UserHome.jsx
Labels: Reviewed

#60 Hot fix user home login
  frontend/src/components/Login.jsx
  frontend/src/pages/UserHome.jsx
Labels: Reviewed

#61 S08 us40 main styling improvements
  frontend/src/App.css
  frontend/src/components/GalleryButton.jsx
  frontend/src/components/NavBar.jsx
  frontend/src/components/NavBarUser.jsx
  frontend/src/pages/AdminHome.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/UserHome.jsx
Labels: Reviewed

#63 S08US42_realdata_implementation: implemented real data in 'database.s…
  backend/database.sql
  frontend/src/pages/Artwork.jsx
Labels: Reviewed

#64 S07 us43 modification settings
  backend/src/controllers/uploadControllers.js
  backend/src/router.js
  frontend/src/components/ConfirmationModal.jsx
  frontend/src/components/DeleteUserConfirmation.jsx
  frontend/src/components/FavoriteButton.jsx
  frontend/src/components/Login.jsx
  frontend/src/components/ModifyProfilePic.jsx
  frontend/src/components/UserCard.jsx
  frontend/src/pages/AccountSettings.jsx
  frontend/src/pages/ArtistAdministration.jsx
  frontend/src/pages/ArtworksAdministration.jsx
  frontend/src/pages/UserFavorite.jsx
  frontend/src/pages/UserHome.jsx
Labels: Reviewed

#65 S07 us43 modification settings
  backend/src/router.js
  frontend/src/components/FavoriteButton.jsx
  frontend/src/pages/UserFavorite.jsx
Labels: Reviewed

#66 S08 us46 jwt
  frontend/src/components/NavBarUser.jsx
  frontend/src/pages/AccountSettings.jsx
Labels: Reviewed

#68 S08 us40 main styling improvements
  frontend/src/components/BurgerMenu.jsx
  frontend/src/components/NavBar.jsx
  frontend/src/components/NavBarUser.jsx
  frontend/src/pages/AccountSettings.jsx
  frontend/src/pages/UserHome.jsx
Labels: Reviewed

#69 S08US50_Artist_carousel:
  frontend/src/components/Carousel.jsx
  frontend/src/pages/Artist.jsx
  frontend/src/pages/Artwork.jsx
Labels: Reviewed

#70 Hot fix delete artist
  backend/public/tmp/0c95f61ce01d6cb488c2bda6ce4518fe
  backend/public/tmp/964f7ac10edf3614eb786a34a31c8de0
  backend/src/router.js
  frontend/src/components/ConfirmationModal.jsx
  frontend/src/components/Login.jsx
  frontend/src/components/ModifyProfilePic.jsx
  frontend/src/pages/AccountSettings.jsx
  frontend/src/pages/ArtistAdministration.jsx
  frontend/src/pages/ArtworksAdministration.jsx
Labels: Reviewed

#71 Hot fix post cloudinary
  frontend/src/components/ConfirmationModal.jsx
  frontend/src/components/ModifyProfilePic.jsx
  frontend/src/pages/AccountSettings.jsx
Labels: Reviewed

#72 Hot fix carousel map key
  frontend/src/components/Carousel.jsx
  frontend/src/components/Login.jsx
  frontend/src/components/NavBar.jsx
  frontend/src/components/NavBarUser.jsx
  frontend/src/pages/Artist.jsx
Labels: Reviewed

#73 S08 us50 artist carousel
  frontend/src/components/Carousel.jsx
Labels: Reviewed

#76 S08 usx3 images resizing
  frontend/src/assets/Fleche droite.png
  frontend/src/assets/Fleche gauche.png
  frontend/src/components/Carousel.jsx
  frontend/src/pages/Artist.jsx
Labels: Reviewed

#77 Pagination
  frontend/src/components/BigPicture.jsx
  frontend/src/components/ValidationModal.jsx
  frontend/src/pages/AccountSettings.jsx
  frontend/src/pages/AdminHome.jsx
  frontend/src/pages/ArtworksAdministration.jsx
  frontend/src/pages/Gallery.jsx
  frontend/src/pages/UserFavorite.jsx
  frontend/src/pages/UsersAdministration.jsx
Labels: Reviewed

#79 Hot fix css mobile artist artwork administration
  backend/database.sql
  frontend/src/pages/ArtistAdministration.jsx
  frontend/src/pages/ArtworksAdministration.jsx
Labels: Reviewed

#80 Hot fix styling improvements
  frontend/src/components/NavBar.jsx
  frontend/src/components/NavBarUser.jsx
  frontend/src/pages/Gallery.jsx
Labels: Reviewed

#81 Hot fix database
  backend/database.sql
Labels: Reviewed

#83 Hot fix add artwork delete artist
  backend/database.sql
  frontend/src/components/ConfirmationModal.jsx
  frontend/src/pages/ArtistAdministration.jsx
  frontend/src/pages/ArtworksAdministration.jsx
Labels: Reviewed

#84 Hot fix width height picture
  frontend/src/pages/ArtworksAdministration.jsx
  frontend/src/pages/Gallery.jsx
  frontend/src/pages/UserFavorite.jsx
Labels: Reviewed

#86 Hot fix close modal modify profile pic
  frontend/src/components/ConfirmationModal.jsx
  frontend/src/components/ModifyProfilePic.jsx
  frontend/src/pages/ArtistAdministration.jsx
  frontend/src/pages/ArtworksAdministration.jsx
Labels: Reviewed

#87 S08 us51 responsive artist page
  backend/database.sql
  frontend/src/assets/Fleche gauche.png
  frontend/src/components/Carousel.jsx
  frontend/src/components/FavoriteButton.jsx
  frontend/src/components/FullDescription.jsx
  frontend/src/pages/About.jsx
  frontend/src/pages/AdminHome.jsx
  frontend/src/pages/Artist.jsx
  frontend/src/pages/Artwork.jsx
  frontend/src/pages/ArtworksAdministration.jsx
Labels: Corrections done, Reviewed

#88 hot_fix_carousel - fix gap artworks carousel
  frontend/src/components/Carousel.jsx
Labels: Reviewed

#90 fixed responsive
  backend/database.sql
  frontend/src/components/FullDescription.jsx
  frontend/src/pages/Artwork.jsx
Labels: Reviewed

#91 S08 us51 delete profile pic
  frontend/src/components/ModifyProfilePic.jsx
  frontend/src/pages/UserHome.jsx
Labels: Reviewed

#93 Hot fix add artworks modal
  frontend/src/components/AddArtwork.jsx
  frontend/src/components/ArtworkFormAdd/ArtworkForm1.jsx
  frontend/src/components/ArtworkFormAdd/ArtworkForm2.jsx
  frontend/src/components/ArtworkFormAdd/ArtworkForm3.jsx
Labels: Reviewed

#95 fixed description issue
  frontend/src/components/FullDescription.jsx
Labels: Reviewed

#96 Hot fix add artworks modal
  frontend/src/components/AddArtwork.jsx
  frontend/src/pages/AccountSettings.jsx
  frontend/src/pages/AdminHome.jsx
  frontend/src/pages/UserHome.jsx
Labels: Reviewed

#98 Hot fix carousel gallery
  frontend/src/components/Carousel.jsx
  frontend/src/pages/Artist.jsx
  frontend/src/pages/Artwork.jsx
  frontend/src/pages/Gallery.jsx
Labels: Reviewed

#101 hot_fix_modify_modal - dimension
  frontend/src/components/ModifyArtist.jsx
  frontend/src/components/ModifyArtwork.jsx
Labels: Reviewed
